local   all             all                                     trust
hostssl dm              dm              all                     cert
hostnossl all           all             all                     reject