local   all             all                                     trust
hostssl all             dm              all                     cert
hostnossl all           all             all                     reject