const ERROR_CODES = {
	INVALID_ARGUMENT: 'INVALID_ARGUMENT',
	FORBIDDEN: 'FORBIDDEN',
	TARGET_USER_NOT_FOUND: 'TARGET_USER_NOT_FOUND',
	NOT_FOUND: 'NOT_FOUND',
	UNAUTHORIZED_CALLER: 'UNAUTHORIZED_CALLER',
	INTERNAL_ERROR: 'INTERNAL_ERROR'
};

module.exports = ERROR_CODES;